# Generated by Django 5.2.11 on 2026-02-16 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=100, verbose_name='Fakultetiň ady')),
                ('gysgaltma', models.CharField(blank=True, max_length=10, verbose_name='Gysgaltma')),
                ('binasy', models.CharField(blank=True, max_length=200, verbose_name='Fakultetiň binasy')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fakultet_logo/', verbose_name='Logotipi')),
                ('gurulan_sene', models.DateField(blank=True, null=True, verbose_name='Gurulan senesi')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetler',
                'ordering': ['ady'],
            },
        ),
        migrations.CreateModel(
            name='SportGornushi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=100, verbose_name='Sport görnüşi')),
                ('toparlygy', models.BooleanField(default=False, verbose_name='Toparlaýyn')),
                ('dusundirish', models.TextField(blank=True, verbose_name='Düşündiriş')),
            ],
            options={
                'verbose_name': 'Sport görnüşi',
                'verbose_name_plural': 'Sport görnüşleri',
            },
        ),
        migrations.CreateModel(
            name='Oyuncu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=50, verbose_name='Ady')),
                ('familiyasy', models.CharField(max_length=50, verbose_name='Familiýasy')),
                ('surat', models.ImageField(blank=True, null=True, upload_to='oyuncular/', verbose_name='Suraty')),
                ('doglan_sene', models.DateField(blank=True, null=True, verbose_name='Doglan senesi')),
                ('kurs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Kursy')),
                ('topar', models.CharField(help_text='Mysal: T-101, M-202', max_length=20, verbose_name='Topary')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon belgisi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiw')),
                ('gosulan_sene', models.DateTimeField(auto_now_add=True, verbose_name='Goşulan sene')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_league.fakultet', verbose_name='Fakulteti')),
                ('esasgy_sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esasgy_oyuncular', to='sport_league.sportgornushi', verbose_name='Esasy sport görnüşi')),
            ],
            options={
                'verbose_name': 'Oýunçy',
                'verbose_name_plural': 'Oýunçylar',
                'ordering': ['familiyasy', 'ady'],
            },
        ),
        migrations.CreateModel(
            name='OyuncuSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tejribe_yyl', models.IntegerField(default=0, verbose_name='Tejribe ýyly')),
                ('derejesi', models.CharField(blank=True, max_length=50, verbose_name='Derejesi (MS, CMS we ş.m.)')),
                ('oyuncu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_league.oyuncu', verbose_name='Oýunçy')),
                ('sport_gornushi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_league.sportgornushi', verbose_name='Sport görnüşi')),
            ],
            options={
                'verbose_name': 'Oýunçynyň sporty',
                'verbose_name_plural': 'Oýunçylaryň sportlary',
                'unique_together': {('oyuncu', 'sport_gornushi')},
            },
        ),
        migrations.AddField(
            model_name='oyuncu',
            name='sport_gornushi',
            field=models.ManyToManyField(through='sport_league.OyuncuSport', to='sport_league.sportgornushi', verbose_name='Sport görnüşleri'),
        ),
        migrations.CreateModel(
            name='Yarys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=200, verbose_name='Ýaryşyň ady')),
                ('baslanjak_sene', models.DateTimeField(verbose_name='Başlanjak senesi')),
                ('gutaryan_sene', models.DateTimeField(blank=True, null=True, verbose_name='Gutarjak senesi')),
                ('yer', models.CharField(max_length=200, verbose_name='Geçirilýän ýeri')),
                ('status', models.CharField(choices=[('planlanan', 'Meýilleşdirilen'), ('dowam_edyar', 'Dowam edýär'), ('tamamlanyldy', 'Tamamlanan')], default='planlanan', max_length=20, verbose_name='Ýagdaýy')),
                ('sport_gornushi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_league.sportgornushi', verbose_name='Sport görnüşi')),
            ],
            options={
                'verbose_name': 'Ýaryş',
                'verbose_name_plural': 'Ýaryşlar',
                'ordering': ['-baslanjak_sene'],
            },
        ),
        migrations.CreateModel(
            name='YarysGatnashyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netije', models.CharField(choices=[('yenis', 'Ýeňiş gazandy'), ('utuldy', 'Ýeňildi'), ('dowam', 'Dowam edýär'), ('gatnashmady', 'Gatnaşmady')], default='dowam', max_length=20, verbose_name='Netije')),
                ('orun', models.IntegerField(blank=True, null=True, verbose_name='Tutan orny')),
                ('bellik', models.TextField(blank=True, verbose_name='Bellik')),
                ('gosulan_sene', models.DateTimeField(auto_now_add=True, verbose_name='Goşulan sene')),
                ('oyuncu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_league.oyuncu', verbose_name='Oýunçy')),
                ('yarys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_league.yarys', verbose_name='Ýaryş')),
            ],
            options={
                'verbose_name': 'Ýaryşa gatnaşyk',
                'verbose_name_plural': 'Ýaryşa gatnaşyklar',
                'unique_together': {('yarys', 'oyuncu')},
            },
        ),
    ]
